### ISSUE TITLE
关于留学的论坛

### ISSUE THREAD

**Issue by sriting** [sayo-melu/xjtlu-resource-list#1]
关于美国留学的同学可以逛“一亩三分地”这个论坛，当然还有就是针对西浦同学的即将上线的“西浦留学圈”微信小程序啦

**Comment by sayo-melu** [comment]
this list now only allow official resource, i plan to add a none-official resource list later (in the same repository), you can pull request to that list, thanks.

**Comment by sayo-melu** [comment]
add two resource at de7f9ae08aa09727d277c6506d54878cf127c538, thanks for your issue.
